# Generated by Django 2.2 on 2023-08-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20230801_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='epmid',
            new_name='e_id',
        ),
        migrations.AddField(
            model_name='detail',
            name='password',
            field=models.CharField(default=12345678, max_length=30),
        ),
        migrations.AddField(
            model_name='detail',
            name='tkn_no',
            field=models.CharField(default='T<built-in function id>', max_length=6),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
