# Generated by Django 4.2.3 on 2023-08-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='category',
            new_name='cate',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AlterField(
            model_name='detail',
            name='e_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tkn_no',
            field=models.CharField(default='T<django.db.models.query_utils.DeferredAttribute object at 0x000001EE037602E0>', max_length=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_time', models.TimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.detail')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menu'),
        ),
    ]
